### ISSUE TITLE
error when running "make"

### ISSUE THREAD

**Issue by codedbymatt** [scottatron/rtl8814AU#1]
root@kali:~/rtl8814au# make
"******************************************"
"NO SKRC,we will use default KSRC"
"******************************************"
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/4.9.0-kali4-amd64/build M=/root/rtl8814au  modules
make[1]: Entering directory '/usr/src/linux-headers-4.9.0-kali4-amd64'
"******************************************"
"NO SKRC,we will use default KSRC"
"******************************************"
  CC [M]  /root/rtl8814au/core/rtw_cmd.o
In file included from /root/rtl8814au/include/drv_conf.h:22:0,
                 from /root/rtl8814au/include/drv_types.h:30,
                 from /root/rtl8814au/core/rtw_cmd.c:22:
/root/rtl8814au/include/autoconf.h:42:0: warning: "RTW_USE_CFG80211_STA_EVENT" redefined
  #define RTW_USE_CFG80211_STA_EVENT /* Indecate new sta asoc through cfg80211_new_sta */
 
<command-line>:0:0: note: this is the location of the previous definition
In file included from /root/rtl8814au/include/drv_types.h:95:0,
                 from /root/rtl8814au/core/rtw_cmd.c:22:
/root/rtl8814au/include/hal_com.h:411:13: error: ‘file_path’ redeclared as different kind of symbol
 extern char file_path[PATH_LENGTH_MAX];
             ^~~~~~~~~
In file included from /usr/src/linux-headers-4.9.0-kali4-common/include/linux/seq_file.h:10:0,
                 from /usr/src/linux-headers-4.9.0-kali4-common/include/linux/pinctrl/consumer.h:17,
                 from /usr/src/linux-headers-4.9.0-kali4-common/include/linux/pinctrl/devinfo.h:21,
                 from /usr/src/linux-headers-4.9.0-kali4-common/include/linux/device.h:24,
                 from /usr/src/linux-headers-4.9.0-kali4-common/include/linux/dmaengine.h:20,
                 from /usr/src/linux-headers-4.9.0-kali4-common/include/linux/netdevice.h:38,
                 from /root/rtl8814au/include/osdep_service_linux.h:35,
                 from /root/rtl8814au/include/osdep_service.h:41,
                 from /root/rtl8814au/include/drv_types.h:32,
                 from /root/rtl8814au/core/rtw_cmd.c:22:
/usr/src/linux-headers-4.9.0-kali4-common/include/linux/fs.h:2724:14: note: previous declaration of ‘file_path’ was here
 extern char *file_path(struct file *, char *, int);
              ^~~~~~~~~
/usr/src/linux-headers-4.9.0-kali4-common/scripts/Makefile.build:298: recipe for target '/root/rtl8814au/core/rtw_cmd.o' failed
make[4]: *** [/root/rtl8814au/core/rtw_cmd.o] Error 1
/usr/src/linux-headers-4.9.0-kali4-common/Makefile:1507: recipe for target '_module_/root/rtl8814au' failed
make[3]: *** [_module_/root/rtl8814au] Error 2
Makefile:150: recipe for target 'sub-make' failed
make[2]: *** [sub-make] Error 2
Makefile:8: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.9.0-kali4-amd64'
Makefile:1635: recipe for target 'modules' failed
make: *** [modules] Error 2

**Comment by scottatron** [comment]
Sorry @anarchyroot this is just a snapshot of the sources I grabbed from the TP-Link site

I don't recall exactly what I did to get this driver working, but I did find this repo useful: https://github.com/diederikdehaas/rtl8814AU

I suspect from this error that it's something to do with the kernel version you're using. I'm running `Linux raspberrypi 4.4.34-v7+ #930 SMP Wed Nov 23 15:20:41 GMT 2016 armv7l GNU/Linux` on a Raspberry Pi Model 2
